services:
  db:
    image: mysql:8.0
    container_name: poss_pager_db
    environment:
      MYSQL_ROOT_PASSWORD: production_password_123
      MYSQL_DATABASE: poss_pager
    volumes:
      - db_data:/var/lib/mysql
      - ./pos-backend/pos_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pproduction_password_123"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - poss_pager_network

  backend:
    build: ./pos-backend
    environment:
      # These OVERRIDE the .env file values automatically
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: production_password_123
      DB_NAME: poss_pager
      JWT_SECRET: prod_secret_key_999
      ALLOWED_ORIGINS: "http://187.127.139.208"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - poss_pager_network
    ports:
      - "8002:8000"

  frontend:
    build: 
      context: ./poss__pager
      args:
        - VITE_API_URL=http://187.127.139.208:8002
    networks:
      - poss_pager_network
    ports:
      - "8080:5173"

volumes:
  db_data:
networks:
  poss_pager_network:
    driver: bridge